### ISSUE TITLE
map_nav_maneger is not working properly

### ISSUE THREAD

**Issue by atankvadi** [RobotnikAutomation/rb1_base_common#3]
I am working on rb1

I am trying to do **mapping, navigation and localization** of robot through **map_nav_manager** node

map_nav_manager node is an internal web server of the robot. I can access this website
through the browser using the address rb1-base:port, where rb1-base is the hostname of the
robot and the port is 9001.

I can do mapping properly without any error.
**map_server** and **localization** are showing perfectly **map** and **location** of robot
but when I am trying with navigation **/move_base/goal** robot is not going in the right desired place, sometimes is going bit offside from the path, sometime going back rather going forward. 

ping all nodes, and all nosed communicating properly
rb1@rb1-demo:~$ **rosnode list**
/rb1_base/amcl
/rb1_base/controller_spawner
/rb1_base/front_laser
/rb1_base/map_nav_manager
/rb1_base/map_server
/rb1_base/mavros
/rb1_base/move_base
/rb1_base/move_base_node/local_costmap/voxel_grid_throttle
/rb1_base/poi_interactive_marker
/rb1_base/poi_interactive_marker_proxy
/rb1_base/poi_manager
/rb1_base/ps4_joy
/rb1_base/rb1_base_pad
/rb1_base/robot_pose_publisher
/rb1_base/robot_state_publisher
/rb1_base/robotnik_base_hw
/rb1_base/rosapi
/rb1_base/rosbridge_websocket
/rb1_base/system_monitor
/rb1_base/system_monitor/localhost/cpu_monitor
/rb1_base/system_monitor/localhost/hdd_monitor
/rb1_base/system_monitor/localhost/mem_monitor
/rb1_base/system_monitor/localhost/net_monitor
/rb1_base/system_monitor/localhost/ntp_monitor
/rb1_base/tf2_web_republisher
/rb1_base/twist_mux
/rosout

even  **rostopic echo /rb1_base/move_base/goal**
**header: 
  seq: 12
  stamp: 
    secs: 1529418190
    nsecs: 409701108
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1529418190
    nsecs: 409668922
  id: "/rb1_base/poi_interactive_marker-12-1529418190.410"
goal: 
  target_pose: 
    header: 
      seq: 0
      stamp: 
        secs: 1529418190
        nsecs: 409564018
      frame_id: "rb1_base_map"
    pose: 
      position: 
        x: 2.33495057675
        y: 0.0843004842579
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.962909507506
        w: 0.269824536234
-----**
**showing this value but robot is not moving.**

Is it calibration problem ? if yes, then any idea how to do calibration on rb1, because I didn't find any topic or rosservice or launch file to calibrate. 

so can anyone tell me how can I fix this?

**Comment by mikekaram** [comment]
Hello @atankvadi , the configuration parameters you could check and modify, are in the rb1_base_common/rb1_base_navigation/config. In the .../launch directory are also the launch files. As for your question, I 'm afraid I cannot help you. The localization and navigation I am doing is explained  in the README file in rb1_base_sim package, so maybe you could start from there.

**Comment by atankvadi** [comment]
I launched bringup file for one robot with navigation and localization as mention in README file 

I am getting warning like 
**[ WARN] [1529481528.799833374, 0.215000000]: updateConfig() called on a dynamic_reconfigure::Server that provides its own mutex. This can lead to deadlocks if updateConfig() is called during an update. Providing a mutex to the constructor is highly recommended in this case. Please forward this message to the node author.
[ INFO] [1529481528.802921040, 0.215000000]: Dynamic Reconfigure:
DynamicParams:
	Odometry parameters:
		left wheel radius: 1
		right wheel radius: 1
		wheel separation: 1
	Publication parameters:
		Publish executed velocity command: 0
		Publication rate: 50
		Publish frame odom on tf: 1**

not only that, even i tried with rqt as well. and try to get  echo from topic 
still i am getting error : dynrecongig client failed , for that I already asked quetion in Robotnik_automation/robotnik_base_hw
https://github.com/RobotnikAutomation/robotnik_base_hw/issues/1

**Comment by RomanRobotnik** [comment]
Hi @atankvadi,
After reading your comments I'm not sure if the problem is that the robot doesn't follow the right path, doesn't finish in the exact goal position or it's not moving at all? or maybe all of this things are happening randomly?

**Comment by atankvadi** [comment]
hii @mikekaram  and @RomanRobotnik 

1)  first case 
If I am trying to navigation through **map_nav_manager** node (for more detail,see question) things are happening randomly.

2)second case
as @mikekaram suggest, I am doing by launch the **roslaunch rb1_base_sim_bringup rb1_base_complete.launch move_base_robot_a:=true amcl_and_mapserver_a:=true**
then it showing the warning which I described in above's comment.
and i am unable to move the robot or see any value from any topic.

3)third case
I tried with **rqt** as well, and also it showing that **dynamic reconfig client failed**
link and more detail of rqt issue in the above's comment

Am I missing anything?
because I can see all node, topic and rosservice but can not see any value from any topic.

**Comment by RomanRobotnik** [comment]
Hi,

If you're using map_nav_manager I guess you are working with the "real" robot, so the launch rb1_base_sim_bringup ... is not going to work properly, because is intended for simulation. 

The last  issue I think you have is that you cannot connect to the ROS_MASTER (the robot) and subscribe/publish to the robot topics correctly. I answered [here](https://github.com/RobotnikAutomation/robotnik_base_hw/issues/1) the way to solve the communication issue. I hope it can solve this part.

**Comment by atankvadi** [comment]
Hii @RomanRobotnik 
it is working now. thank you for your comment.
since I know ROS, I only worked on simulator, not with real robot.
when I am trying to run rviz it saying that 
**parameter [robot_description] does not exist, and not found by searchparam**
 then I made some changes in rb1_base_gazebo and created new launch file.
```

<?xml version="1.0"?>
<launch>


	<arg name="launch_rviz" default="true"/>
	<arg name="launch_robot_a" default="true"/>

	<arg name="debug" default="false"/>

	<!--params of the different robots-->
	<!-- robot a -->
	<arg name="id_robot_a" default="rb1_base_a"/>
	<arg name="x_init_pose_robot_a" default="0" />
	<arg name="y_init_pose_robot_a" default="0" />
	<arg name="z_init_pose_robot_a" default="0" />
	<arg name="localization_robot_a" default="false"/>
	<arg name="gmapping_robot_a" default="false"/>
	<arg name="move_base_robot_a" default="false"/>
	<arg name="amcl_and_mapserver_a" default="false"/>
	<arg name="map_file_a" default="$(find rb1_base_localization)/maps/mcq/mcq-scan-office.yaml"/>
	<arg name="map_frame_a" default="$(arg id_robot_a)_map"/>
	<arg name="xacro_robot_a" default="rb1_base_std.urdf.xacro"/>	

	
	<!--BEGIN ROBOT 1-->
	<include if="$(arg launch_robot_a)" file="$(find rb1_base_gazebo)/launch/rb1_base_one_robot.launch">
		<arg name="id_robot" value="$(arg id_robot_a)"/>
		<arg name="x_init_pose" value="$(arg x_init_pose_robot_a)"/>
		<arg name="y_init_pose" value="$(arg y_init_pose_robot_a)"/>
		<arg name="z_init_pose" value="$(arg z_init_pose_robot_a)"/>
		<arg name="xacro_robot" value="$(arg xacro_robot_a)"/>
		<arg name="launch_robot_localization" value="$(arg localization_robot_a)"/>
		<arg name="launch_amcl_and_mapserver" value="$(arg amcl_and_mapserver_a)"/>
		<arg name="launch_gmapping" value="$(arg gmapping_robot_a)"/>
		<arg name="map_file" value="$(arg map_file_a)"/>
 		<arg name="launch_move_base" value="$(arg move_base_robot_a)"/>
		<arg name="global_frame" value="$(arg map_frame_a)"/>

	</include>

	<!-- gazebo simulation and rviz visualization-->
	<include file="$(find rb1_base_gazebo)/launch/gazebo_rviz.launch">		
		<arg name="launch_rviz" value="$(arg launch_rviz)"/>
		
		<arg name="debug" value="$(arg debug)"/>
	</include>

  
</launch>
```





then missing frame is ,  rb1_base_odom topic in rviz
Actually I am new at ROS, so please let me know where i am wrong.

**Comment by atankvadi** [comment]
Also I found that when I publish the topic 
rostopic echo /rb1_base/cmd_vel geometry_msgs/Twist -r 1 '[1.0, 0.0. 0.0]' '[0.0, 0.0, 0.0]'

robot is moving straight  but robot is not moving smoothly, it is going and stop for second then going.

**Comment by RomanRobotnik** [comment]
This is because the robot controller implements a "watchdog" mechanism that stops the motors if it doesn't receive any command in 'x' ms. You have to publish at higher frequency. Try with:

rostopic echo /rb1_base/cmd_vel geometry_msgs/Twist -r **20** '[1.0, 0.0. 0.0]' '[0.0, 0.0, 0.0]'
